bookmark/__init__.py
"""
Bookmark flask app
"""
from flask import Flask
from flask_login import LoginManager
from flask_debugtoolbar import DebugToolbarExtension
from bookmark.config import Configuration

app = Flask(__name__, static_folder=Configuration.STATIC_FOLDER)
app.config.from_object('bookmark.config.Configuration')
app.config.from_envvar('SALMON_LOCAL_SETTINGS', silent=True)

login_manager = LoginManager()
login_manager.init_app(app)

if app.config['DEBUG']:
    toolbar = DebugToolbarExtension(app)

from bookmark.blueprint import api
from bookmark.blueprint import web
from bookmark.blueprint import login

app.register_blueprint(api, url_prefix='/api')
app.register_blueprint(web, url_prefix='/')
app.register_blueprint(login, url_prefix='/user')

bookmark/blueprint/__init__.py
from .api import b as api
from .web import b as web
from .login import b as login
from bookmark import app
from flask.templating import render_template


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

bookmark/blueprint/api/__init__.py
from flask import Blueprint, request, jsonify, session
from functools import wraps
from bookmark import service

from bookmark import app
from bookmark.service import get_tagcloud, get_tag, get_list_bookmark

from tagscloud import process_tag_count
from .item.Bookmark import ItemBookmark
from .item.Tag import ItemTag
from .form import BookmarkForm

from sqlalchemy.exc import IntegrityError

b = Blueprint('api', __name__)


@b.route('/', methods=['GET', ])
def index():
    return VERSION


@b.route('/bookmarks/', methods=['GET', ])
@b.route('/bookmarks/<string:tags>', methods=['GET', ])
def bookmarks(tags=None):
    filters = []
    if tags is not None:
        filters = [x.id for x in
            [get_tag(x) for x in tags.split(app.config['SEPARATOR'])]
            if x is not None]

    page = int(request.args.get('page', "1"))

    bookmarks = get_list_bookmark(filter=filters, page=page, per_page=app.config['PER_PAGE'])
    total = get_list_bookmark(filters, count=True)
    bookmark_list = []

    for b in bookmarks:
        bookmark = ItemBookmark(b.id, b.tags, b.link, b.title, b.description)
        bookmark_list.append(bookmark)

    bookmark_list = map(lambda x: x.json(), bookmark_list)
    ret = {
        "bookmarks": bookmark_list,
        "page": page,
        "per_page": app.config['PER_PAGE'],
        "total": total,
    }

    return jsonify(ret)


@b.route('/bookmarks/<int:id>', methods=['PUT', ])
def update_bookmark(id):
    form = BookmarkForm(request.json, id=id)
    if form.validate_on_submit():
        service.edit_bookmark(form.bookmark)
        ret = {}
    else:
        ret = {
            "errors": form.errors
        }
    #BookmarkForm().reset_csrf()
    ret["csrf"] = session.get(app.config['CSRF_SESSION_KEY'])
    return jsonify(ret)


@b.route('/bookmarks/', methods=['POST', ])
def add_bookmark():
    form = BookmarkForm(request.json)
    ret = None
    if form.validate_on_submit():
        try:
            service.add_bookmark(form.bookmark)
            ret = {}
        except IntegrityError, e:
            errors = []
            if e.message == '(IntegrityError) column link is not unique':
                errors.append("Link alredy exists")
            ret = {
                "errors": {
                    "link": errors,
                }
            }
    else:
        ret = {
            "errors": form.errors,
        }

    BookmarkForm().reset_csrf()
    ret["csrf"] = session.get(CSRF_SESSION_KEY)
    return jsonify(ret)


@b.route('/tagcloud', methods=['GET', ])
@b.route('/tagcloud/<string:tags>', methods=['GET', ])
def tagcloud(tags=None):
    filters = []
    filters_tags = []
    if tags is not None:
        query_list = [get_tag(x) for x in tags.split(app.config['SEPARATOR'])]
        filters_tags = map(lambda x: ItemTag(pid=x.id, pname=x.name,
            pfilter=True), query_list)
        filters = map(lambda x: x.id, query_list)

    cloud = get_tagcloud(filters)
    tags_list = [ItemTag(t.id, t.name, count).json() for t, count in cloud]
    process_tag_count(tags_list, max_percent=30, min_percent=11)
    tags_list = {"tags": [x.json() for x in filters_tags] + tags_list}

    return jsonify(tags_list)

bookmark/blueprint/api/form/__init__.py
from flask_wtf import Form
from flask_wtf import HiddenField
from flask_wtf import TextField
from flask_wtf import validators
from flask_wtf import TextAreaField
from flask_wtf import SubmitField
from flask_wtf.html5 import URLField
from bookmark.blueprint.api.item.Bookmark import ItemBookmark
from werkzeug.datastructures import MultiDict
from bookmark.service import get_bookmark_by_id

from flask import abort


class AjaxForm(Form):
    def __init__(self, formdata=None, *args, **kwargs):
        if formdata is not None:
            formdata = MultiDict(formdata.items())
        super(AjaxForm, self).__init__(formdata, *args, **kwargs)


class BookmarkForm(AjaxForm):
    id = HiddenField(u'Id')
    link = URLField(u'Link', validators=[validators.required(),
        validators.url(), ])
    title = TextField(u'Title', validators=[validators.required(), ])
    description = TextAreaField(u'Description')
    tags = TextField(u'Tags')
    submit = SubmitField(u'Add')
    edit = SubmitField(u'Edit')

    def __init__(self, formdata=None, *args, **kwargs):
        self.id.data = kwargs.get('id', None)
        super(BookmarkForm, self).__init__(formdata, *args, **kwargs)

    def validate(self):
        rv = Form.validate(self)
        if not rv:
            return False

        _id = self.id.data
        link = self.link.data
        title = self.title.data
        description = self.description.data
        tags = map(lambda x: {'name': x.strip()}, self.tags.data.split(','))

        if _id is None or _id == '' or int(_id) < 1:
            self.bookmark = ItemBookmark(tags=tags, link=link, title=title,
                description=description)
        else:
            self.bookmark = get_bookmark_by_id(_id)
            if self.bookmark is None:
                abort(404)
            self.bookmark.title = title
            self.bookmark.description = description
            self.bookmark.set_tags(tags)

        return True

bookmark/blueprint/login/__init__.py
from .form import LoginForm
from .form import RegisterForm
from flask import Blueprint
from flask import redirect
from flask import url_for
from flask import request
import bookmark
from flask_login import login_user
from flask_login import logout_user
from flask.templating import render_template
from bookmark.service import add_user
from bookmark.service import get_user_by_id

b = Blueprint('user', __name__)

login_manager = bookmark.login_manager


@login_manager.user_loader
def load_user(userid):
    return get_user_by_id(userid)


@b.route('/login', methods=['GET', 'POST', ])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # login and valide the user...
        login_user(form.user, remember=form.remember.data)
        return redirect(request.args.get('next') or url_for('web.index'))
    return render_template('login.html', form=form)


@b.route('/register', methods=['GET', 'POST', ])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # register if ok
        add_user(form.user)
        return redirect(url_for('web.index'))
    return render_template('register.html', form=form)


@b.route('/logout', methods=['GET', ])
def logout():
    logout_user()
    return redirect(url_for('web.index'))

bookmark/blueprint/login/form/__init__.py
from flask_wtf import Form
from flask_wtf import validators
from flask_wtf import TextField, PasswordField, SubmitField
from flask_wtf import BooleanField
from flask_wtf import ValidationError
from bookmark.model import User
from bookmark import app
from bookmark.service import count_user_by_pseudo
from bookmark.service import check_password


def unique_user(form, field):
    """
    Check if user's pseudo is not already used.
    """
    if count_user_by_pseudo(field.data) > 0:
        raise ValidationError("Pseudo unavailable.")


def user_exists(form, field):
    if count_user_by_pseudo(field.data) == 0:
        raise ValidationError("Does not exists.")


class LoginForm(Form):
    def __init__(self, *args, ** kwargs):
        Form.__init__(self, *args, ** kwargs)
        self.user = None

    login = TextField(u'Login', validators=[validators.required(), ])
    password = PasswordField(u'Password', validators=[validators.required(), ])
    remember = BooleanField(u'Remember me')
    submit = SubmitField(u'Validate')

    def validate(self):
        rv = Form.validate(self)
        if not rv:
            return False

        pseudo = self.login.data
        password = self.password.data

        try:
            user_exists(self, self.login)
            user = check_password(pseudo, password)
            if user is None:
                self.password.errors.append('Wrong password.')
                return False
        except ValidationError:
            self.login.errors.append('Unknow user.')
            return False

        self.user = user

        return True


class RegisterForm(Form):
    login = TextField(u'Login', validators=[validators.required(),
        unique_user, ])
    password = PasswordField(u'Password', validators=[validators.required(),
        validators.length(min=app.config['MIN_PASSWORD_LENGTH']), ])
    password_confirmation = PasswordField(u'Password confirmation',
        validators=[validators.required(),
        validators.length(min=app.config['MIN_PASSWORD_LENGTH']), ])
    submit = SubmitField(u'Register')

    def __init__(self, *args, ** kwargs):
        Form.__init__(self, *args, ** kwargs)
        self.user = None

    def validate(self):
        rv = Form.validate(self)
        if not rv:
            return False

        pseudo = self.login.data
        password = self.password.data
        password_confirmation = self.password_confirmation.data

        if password != password_confirmation:
            self.password.errors.append('Passwords mismatch')
            self.password_confirmation.errors.append('Passwords mismatch')
            return False

        self.user = User(pseudo, password)

        return True

bookmark/blueprint/web/__init__.py
from flask import Blueprint
from flask import render_template
from flask import request, url_for

from bookmark.blueprint.api.form import BookmarkForm
from werkzeug.contrib.atom import AtomFeed
from bookmark.service import get_list_bookmark

b = Blueprint('web', __name__)


@b.route('/', methods=['GET', ])
def index():
    form = BookmarkForm(create=True)
    return render_template('index.html', form=form)

@b.route('feed/news.xml')
def new_bookmarks_feed():
    feed = AtomFeed('Recent bookmarks', feed_url=request.url,
        url=url_for('web.index'))
    bookmarks = get_list_bookmark(page=0, per_page=20)
    for bookmark in bookmarks:
        feed.add(bookmark.title, unicode(bookmark.description),
            content_type='html', url=bookmark.link,
            updated=bookmark.update_time,
            published=bookmark.update_time)
    return feed.get_response()

bookmark/model/__init__.py
from flask_sqlalchemy import SQLAlchemy

from bookmark import app
import logging
from werkzeug.security import generate_password_hash
from flask_login import UserMixin

from sqlalchemy import func

db = SQLAlchemy(app)

logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

tags = db.Table('bookmark_tag',
    db.Column('bookmark_id', db.Integer, db.ForeignKey('bookmark.id'),
        nullable=False),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), nullable=False)
)


class Bookmark(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    tags = db.relationship('Tag', secondary=tags,
        backref=db.backref('bookmarks', lazy='dynamic'))
    link = db.Column(db.String(255), unique=True)
    title = db.Column(db.String(100), nullable=False)
    description = db.Column(db.Text(), nullable=False)
    update_time = db.Column(db.DateTime(), db.DefaultClause(func.now()),
        nullable=False)

    def __init__(self, tags=None, link=None, title=None, description=None):
        self.tags = tags if tags is not None else []
        self.link = link
        self.title = title
        self.description = description

    def __repr__(self):
        return '<Bookmark (%d, %s %s) %s>' % (self.id, self.title, self.link,
            self.tags)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True, nullable=False)

    def __init__(self, pname):
        self.name = pname

    def __repr__(self):
        return '<Tag (%d, %s)>' % (self.id, self.name)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    pseudo = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)

    def __init__(self, pseudo, password):
        self.pseudo = pseudo
        self.password = generate_password_hash(password,
            salt_length=app.config['SALT_LENGTH'])

bookmark/service/__init__.py
from bookmark.model import Bookmark, Tag, db, User
from werkzeug.security import generate_password_hash
from werkzeug.security import check_password_hash
from sqlalchemy import func
from bookmark.blueprint.api.item.Bookmark import ItemBookmark


def convert_bookmark(bookmark, b=None):
    if b is None:
        b = Bookmark()
    b.id = bookmark._id
    b.link = bookmark.link
    b.title = bookmark.title
    b.description = bookmark.description
    b.tags = []
    if bookmark.tags is not None:
        for tag in bookmark.tags:
            b.tags.append(get_tag_or_create(tag))
    return b


def get_tag_or_create(name):
    """
    return a tag, create it if it does not currently exist
    """
    tag = get_tag(name)
    if tag is None:
        tag = Tag(name)
        db.session.add(tag)
        db.session.commit()
    return tag


def get_tag(name):
    return Tag.query.filter_by(name=name).first()


def get_tagcloud(filter=None):
    bookmark_tag = db.metadata.tables['bookmark_tag']
    query = db.session.query(Tag, func.count(Tag.id))\
        .filter(Tag.id == bookmark_tag.c.tag_id)
    if filter is not None and len(filter) > 0:
        subquery = db.session.query(Bookmark.id)\
            .filter(Bookmark.id == bookmark_tag.c.bookmark_id)\
            .filter(bookmark_tag.c.tag_id.in_(filter))\
            .group_by(Bookmark.id)\
            .having(func.count(Bookmark.id) == len(filter)).subquery()

        query = query.filter(bookmark_tag.c.bookmark_id == subquery.c.id)\
            .filter(~Tag.id.in_(filter))
    return query.group_by(Tag.id).all()


def get_bookmark_by_id(id):
    bookmark = Bookmark.query.get(id)

    ret = ItemBookmark()

    ret._id = bookmark.id
    ret.tags = ", ".join([x.name for x in bookmark.tags])
    ret.title = bookmark.title
    ret.description = bookmark.description
    ret.link = bookmark.link
    return ret


def get_list_bookmark(filter=None, count=False, page=None, per_page=None):
    """
    solution pour le count, faire une sous requete qui sera ensuite
    utilise par le count de la requette principale
    """

    query = Bookmark.query if not count else db.session.query(Bookmark.id)
    if filter is not None and len(filter) > 0:
        bookmark_tag = db.metadata.tables['bookmark_tag']
        query = query.filter(Bookmark.id == bookmark_tag.c.bookmark_id)\
            .filter(bookmark_tag.c.tag_id.in_(filter))\
            .group_by(Bookmark.id)\
            .having(func.count(Bookmark.id) == len(filter))

    if page is not None and per_page is not None:
        offset_value = (page - 1) * per_page
        query = query.order_by(Bookmark.update_time.desc())\
            .limit(per_page)\
            .offset(offset_value)
    if count:
        subquery = query.subquery()
        return db.session.query(func.count(Bookmark.id))\
            .filter(Bookmark.id == subquery.c.id).all()[0][0]
    else:
        return query.all()


def add_bookmark(bookmark):
    b = convert_bookmark(bookmark)
    db.session.add(b)
    db.session.commit()


def edit_bookmark(bookmark):
    old = Bookmark.query.get(bookmark._id)
    convert_bookmark(bookmark, old)
    print "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    print old
    db.session.commit()


def add_user(user):
    """
    Add an user.
    @param user user model object.
    """
    db.session.add(user)
    db.session.commit()


def count_user_by_pseudo(pseudo):
    """
    @param pseudo A pseudo
    Count number of user with the defined pseudo.
    """
    return db.session.query(func.count(User.id))\
        .filter(User.pseudo == pseudo).first()[0]


def check_password(pseudo, password):
    """
    @param pseudo A pseudo
    @param password A password
    @return None is unknow user or wrong password, user model object otherwire.
    Check if pseudo and password match an user.
    """
    ret = None

    supposed_user = User.query.filter_by(pseudo=pseudo).first()
    if supposed_user is not None:
        if check_password_hash(supposed_user.password, password):
            ret = supposed_user

    return ret


def get_user_by_id(userid):
    return User.query.get(userid)

bookmark/templates/base.html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{% block head_title %}{% endblock %}</title>
    {% block head_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% endblock %}
    {% block head_js %}{% endblock %}
    {% block head_rss %}{% endblock %}
</head>
<body>
{% include "menu.html" %}
<div id="container" class="container">
{% block content %}{% endblock %}
</div>
{# rendre configurable #}
<input type="hidden" id="api_root" value="{{config.API_ROOT}}" />
</body>
</html>

bookmark/templates/index.html
{% extends "base.html" %}
{% from "macros/_textfield.html" import render_textfield %}
{% block head_js %}
<script type="text/javascript" src="{{ url_for('static', filename='js/underscore-min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/backbone-min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/app.js') }}"></script>
{% endblock %}
{% block head_rss %}
<link rel="alternate" type="application/rss+xml" title="Recent bookmarks" href="{{ url_for('web.new_bookmarks_feed') }}" />

{% endblock %}
{% block content %}
<h1>Cloud</h1>
<div class="row span16">
    <div>
        Filters :
        <span id="tags-filter"></span>
    </div>
    <div id="tagscloud"></div>
</div>
<h1>Bookmarks</h1>
<div id="bookmarks" class="row span16"></div>
<div id="pagination-bookmarks"></div>
<div id="bookmark-form-modal" class="modal hide fade"></div>
<div class="hide">
    {# 
    hidden field which contains currents csrf token, copied where needed
    in case of form submission
    #}
    <input type="hidden" id="bookmark-csrf" value="{{ form.csrf_token }}" />
</div>

{#
we can't use eco coffee script template library because most
of the form is generated by jinja + wtform.
I guess we can generate it once and copy it in an eco template file but
it is not a convenient solution imho.
#}
<script type="text/template" id="bookmark-form-modal-template">
    <form action="{{ url_for('api.add_bookmark') }}">
    {{ form.hidden_tag() }}
    <div class="modal-header">
        <a href="#" class="close">×</a>
        <h3 class="create">Add a bookmark</h3>
        <h3 class="update">Edit a bookmark</h3>
    </div>
    <div class="modal-body"> 
        <p id="global-errors"></p>
        {{ render_textfield(form.link) }}
        {{ render_textfield(form.title) }}
        {{ render_textfield(form.description) }}
        {{ render_textfield(form.tags) }}
    </div>
    <div class="modal-footer">
        {{ form.submit(class_="btn primary create") }}
        {{ form.edit(class_="btn primary update") }}
    </div>
    </form>
</script>
<script type="text/javascript">
	require('main');
</script>
{% endblock %}

bookmark/templates/login.html
{% extends "base.html" %}
{% from "macros/_textfield.html" import render_textfield %}
{% block content %}
<form method="POST" action="">
	{{ form.hidden_tag() }}
    <fieldset>
        <legend>Login</legend>
        {{ render_textfield(form.login) }}
        {{ render_textfield(form.password) }}
        <div class="clearfix">
            <div class="input">
                <ul class="inputs-list">
                    <li>
                        {{ form.remember }} {{ form.remember.label }}
                    </li>
                </ul>
            </div> 
        </div>
        <div class="actions">
    	    {{ form.submit }}
        </div>
    </fieldset>
</form>
{% endblock %}

bookmark/templates/menu.html
<div class="topbar">
    <div class="topbar-inner">
        <div class="container">
            <a href="{{ url_for('web.index') }}" class="brand">Bookmark</a>
            <ul class="nav">
                {# <li><a href="#about">About</a></li> #}
                {% if current_user.is_authenticated() %}
                <li>
                    <a href="#" data-controls-modal="bookmark-form-modal" id="add-bookmark">
                        Add a bookmark
                    </a>
                </li>
                <li><a href="{{ url_for("user.logout") }}">Logout</a></li>
                {% else %}
                <li><a href="{{ url_for("user.login") }}">Login</a></li>
                <li><a href="{{ url_for("user.register") }}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

bookmark/templates/register.html
{% extends "base.html" %}
{% from "macros/_textfield.html" import render_textfield %}
{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset>
        <legend>Register</legend>
        {{ render_textfield(form.login) }}
        {{ render_textfield(form.password) }}
        {{ render_textfield(form.password_confirmation) }}
        <div class="actions">
            {{ form.submit }}
        </div>
    </fieldset>
</form>
{% endblock %}